version: "3.8"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      MONGO_URL: mongodb://mongo:27017/warehouse

  worker:
    build: ./backend
    restart: unless-stopped
    command: ["node", "src/workers/sync.worker.js"]
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      MONGO_URL: mongodb://mongo:27017/warehouse

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mongo-data:
